# ==============================================================================================================================
# Layer Rules
layerrule = blur,rofi
layerrule = blur,logout_dialog
layerrule = blur,bar-0
layerrule = blur,sherlock

layerrule = blur,waybar
layerrule = ignorezero, waybar

layerrule = blur,gtk4-layer-shell
layerrule = ignorezero, gtk4-layer-shell

layerrule = blur,notifications
layerrule = ignorezero, notifications
layerrule = animation slide, notifications

layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = animation popin 95%, swaync-control-center

layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = animation slide, swaync-notification-window

layerrule = blur, rightPanel
layerrule = ignorezero, rightPanel
layerrule = animation slide, rightPanel