# ==============================================================================================================================
# Layer Rules
layerrule = blur,rofi
layerrule = blur,fabric
layerrule = blur,logout_dialog
layerrule = blur,bar-0
layerrule = blur,waybar
layerrule = blur,notifications
layerrule = blur,^(ignis_bar.*)$
layerrule = ignorezero, notifications
layerrule = ignorezero, waybar

layerrule = blur, swaync-control-center
layerrule = ignorezero, swaync-control-center
layerrule = animation popin 95%, swaync-control-center

layerrule = blur, swaync-notification-window
layerrule = ignorezero, swaync-notification-window
layerrule = animation slide, swaync-notification-window
