# ==============================================================================================================================
# Layer Rules
layerrule = blur,rofi
layerrule = blur,logout_dialog
layerrule = blur,bar-0
layerrule = blur,sherlock

layerrule = blur,waybar
layerrule = ignorezero, waybar

layerrule = blur,gtk4-layer-shell
layerrule = ignorezero, gtk4-layer-shell

layerrule = blur,notifications
layerrule = ignorezero, notifications
layerrule = animation slide, notifications

layerrule = blur, quickshell
layerrule = ignorezero, quickshell