source = ~/.config/hypr/themes/catppuccin-frappe.conf

plugin:overview{
    onBottom = 1
    workspaceActiveBorder = $foreground
    panelColor = $backgroundT
    panelHeight = 200
}

bind = Alt_L, TAB, overview:toggle, all                                         # Open Overview
