source = ~/.config/hypr/themes/catppuccin-frappe.conf

plugin:overview{
    onBottom = 1
    workspaceActiveBorder = $foreground
    panelColor = $backgroundT
    panelHeight = 200
}

# chromakey_background = 48,52,70
# windowrulev2 = plugin:chromakey,fullscreen:0
# windowrulev2 = plugin:chromakey,class:^(org.gnome.Nautilus):0

# bind = $mainMod, O, togglechromakey
bind = Alt_L, TAB, overview:toggle, all                                         # Open Overview