source = ~/.config/hypr/themes/current.conf

plugin:overview{
    onBottom = 1
    workspaceActiveBorder = $foreground
    panelColor = $backgroundT
    panelHeight = 200
}

windowrulev2 = plugin:chromakey,fullscreen:0
# chromakey_background = rgb(303446)
